name: Publish libraries to Maven Central

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java, Maven and Sonatype credentials
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          server-id: central
          server-username: ${{ secrets.SONATYPE_USERNAME }}
          server-password: ${{ secrets.SONATYPE_TOKEN }}
          # GPG kulcsot manuálisan importáljuk a következő lépésben

      - name: Import GPG private key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Publish sb-repl-bridge to Maven Central
        run: mvn -B -f sb-repl-bridge/pom.xml clean deploy -Dgpg.keyname=${{ secrets.GPG_KEYNAME }} -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

      - name: Publish sb-repl-agent to Maven Central
        run: mvn -B -f sb-repl-agent/pom.xml clean deploy -Dgpg.keyname=${{ secrets.GPG_KEYNAME }} -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
